services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    networks:
    - testing_net
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  gateway:
    container_name: gateway
    image: gateway:latest
    environment:
      PORT: 3000
      LOG_LEVEL: INFO
      LISTEN_BACKLOG: '5'
      RABBITMQ_HOST: rabbitmq
      INPUT_QUEUE_1: results-queue
      OUTPUT_QUEUE_2: stores-q3-queue-1
      OUTPUT_QUEUE_3: stores-q3-queue-2
      OUTPUT_QUEUE_4: stores-q3-queue-3
      OUTPUT_QUEUE_5: stores-q4-queue-1
      OUTPUT_QUEUE_6: stores-q4-queue-2
      OUTPUT_QUEUE_7: stores-q4-queue-3
      OUTPUT_QUEUE_8: menu-items-queue-1
      OUTPUT_QUEUE_9: menu-items-queue-2
      OUTPUT_QUEUE_10: menu-items-queue-3
      OUTPUT_QUEUE_11: users-queue
      OUTPUT_QUEUE_12: batches-queue
      EXCHANGE_NAME: gateway-exchange
    depends_on:
      rabbitmq:
        condition: service_healthy   
    networks:
    - testing_net

  filter-year:
    container_name: filter-year
    image: filter:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      INPUT_QUEUE_1: batches-queue
      LOG_LEVEL: INFO
    networks:
    - testing_net
    depends_on:
    - gateway

  client:
    container_name: client
    image: client:latest
    environment:
      GATEWAY_HOST: gateway
      GATEWAY_PORT: 3000
      LOG_LEVEL: INFO
      STORES_FOLDER_PATH: data/stores/
      MENU_ITEMS_FOLDER_PATH: data/menu_items/
      USERS_FOLDER_PATH: data/users/
      TRANSACTIONS_FOLDER_PATH: data/transactions/
      TRANSACTION_ITEMS_FOLDER_PATH: data/transaction_items/
      MAX_BATCH_SIZE: 8024
    depends_on:
      - gateway
    networks:
    - testing_net
    volumes:
    - ./client/data/menu_items/:/data/menu_items/
    - ./client/data/stores/:/data/stores/
    - ./client/data/users/:/data/users/
    - ./client/data/transactions/:/data/transactions/
    - ./client/data/transaction_items/:/data/transaction_items/

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24