# Message sizes
MESSAGE_SIZE_BYTES = 4
# Message types
MESSAGE_TYPE_EOF = 0
MESSAGE_TYPE_MENU_ITEMS = 1
MESSAGE_TYPE_STORES = 2
MESSAGE_TYPE_TRANSACTION_ITEMS = 3
MESSAGE_TYPE_TRANSACTIONS = 4
MESSAGE_TYPE_USERS = 5
# Message csv item amount
MESSAGE_CSV_MENU_ITEMS_AMOUNT = 7
MESSAGE_CSV_STORES_AMOUNT = 8
MESSAGE_CSV_TRANSACTION_ITEMS_AMOUNT = 6
MESSAGE_CSV_TRANSACTIONS_AMOUNT = 9
MESSAGE_CSV_USERS = 4