# Message sizes
MESSAGE_SIZE_BYTES = 4
# Message types
MESSAGE_TYPE_EOF = 0
MESSAGE_TYPE_MENU_ITEMS = 1
MESSAGE_TYPE_STORES = 2
MESSAGE_TYPE_TRANSACTION_ITEMS = 3
MESSAGE_TYPE_TRANSACTIONS = 4
MESSAGE_TYPE_USERS = 5
MESSAGE_TYPE_REQUEST_ID = 6
MESSAGE_TYPE_QUERY_1_RESULT = 7
MESSAGE_TYPE_QUERY_3_INTERMEDIATE_RESULT = 8
MESSAGE_TYPE_QUERY_3_RESULT = 9
MESSAGE_TYPE_QUERY_2_INTERMEDIATE_RESULT = 10
MESSAGE_TYPE_QUERY_2_RESULT = 11
MESSAGE_TYPE_QUERY_4_INTERMEDIATE_RESULT = 12
MESSAGE_TYPE_QUERY_4_RESULT = 13
MESSAGE_TYPE_CLIENT_ID = 14
# Message csv item amount
MESSAGE_CSV_MENU_ITEMS_AMOUNT = 7
MESSAGE_CSV_STORES_AMOUNT = 8
MESSAGE_CSV_TRANSACTION_ITEMS_AMOUNT = 6
MESSAGE_CSV_TRANSACTIONS_AMOUNT = 9
MESSAGE_CSV_USERS = 4
# Queries num
QUERY_1 = 'q1'
QUERY_2 = 'q2'
QUERY_3 = 'q3'
QUERY_4 = 'q4'

MAX_PROFIT = 'profit_sum'
MAX_QUANTITY = 'sellings_qty'

# Sub-message constants
SUB_MESSAGE_MULTIPLIER = 100
SUB_MESSAGE_START_ID = 1